version: "3"
services:
  user-api-db:
    build: ./user-api-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      LOAD_DATA: $LOAD_DATA
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - ./data-user-api:/var/lib/mysql

  adventurer-api-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3307:3306
    volumes:
      - ./data-adventurer-api:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOSTS=user-api-db,adventurer-api-db
    restart: always
    depends_on:
     - user-api-db
     - adventurer-api-db
    ports:
     - 8888:80

  mail-server:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8889:8025
