version: "3"
services:
  user-api-db:
    container_name: user-api-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - ./volumes/user-api-data:/var/lib/mysql

  adventurer-api-db:
    container_name: adventurer-api-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - 3307:3306
    volumes:
      - ./volumes/adventurer-api-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
    restart: always
    depends_on:
     - user-api-db
     - adventurer-api-db
    ports:
     - 8888:80