swagger: '2.0'
info:
  description: A simple adventurer API
  version: '1.0.0'
  title: AMT Adventurer API
host: loacalhost:8080
basePath: /api
schemes:
  - http
paths:
  /adventurers:
    get:
      operationId: getAdventurers
      summary: Get adventurers information
      parameters:
        - $ref: '#/parameters/Limit'
        - $ref: '#/parameters/Offset'
        - $ref: '#/parameters/SortBy'
        - $ref: '#/parameters/Populate'
      responses:
        200:
          description: adventurers
          schema:
            type: array
            items:
              $ref: '#/definitions/Adventurer'
    post:
      operationId: createAdventurer
      summary: Create a new adventurer
      parameters:
        - name: adventurer
          in: body
          required: true
          schema:
            $ref: '#/definitions/AdventurerCreate'
      security:
        - Bearer: []
      responses:
        200:
          description: adventurer creation success
          schema:
            $ref: '#/definitions/Adventurer'
        400:
          description: adventurer creation failed
        403:
          description: unauthorized access
  /adventurers/{name}:
    get:
      operationId: getAdventurer
      summary: Get an adventurer information
      parameters:
        - $ref: '#/parameters/Name'
        - $ref: '#/parameters/Populate'
      responses:
        200:
          description: adventurer information
          schema:
            $ref: '#/definitions/Adventurer'
        404:
          description: adventurer not found
    put:
      operationId: updateAdventurer
      summary: Update adventurer information
      parameters:
        - $ref: '#/parameters/Name'
        - name: information
          in: body
          required: true
          schema:
            $ref: '#/definitions/AdventurerUpdate'
      security:
        - Bearer: []
      responses:
        200:
          description: adventurer updated
          schema:
            $ref: '#/definitions/Adventurer'
        403:
          description: unauthorized access
        404:
          description: adventurer not found
    delete:
      operationId: deleteAdventurer
      summary: Deletes an adventurer
      parameters:
        - $ref: '#/parameters/Name'
      security:
        - Bearer: []
      responses:
        200:
          description: adventurer deleted
        403:
          description: unauthorized access
        404:
          description: adventurer not found
  /quests:
    get:
      operationId: getQuests
      summary: Get quests information
      parameters:
        - $ref: '#/parameters/Limit'
        - $ref: '#/parameters/Offset'
        - $ref: '#/parameters/Populate'
      responses:
        200:
          description: quests
          schema:
            type: array
            items:
              $ref: "#/definitions/Quest"
    post:
      operationId: createQuest
      summary: Create a new quest
      parameters:
        - name: quest
          in: body
          required: true
          schema:
            $ref: '#/definitions/QuestCreate'
      security:
        - Bearer: []
      responses:
        200:
          description: quest creation success
          schema:
            $ref: '#/definitions/Adventurer'
        400:
          description: quest creation failed
        403:
          description: unauthorized access
  /quests/{id}:
    get:
      operationId: getQuest
      summary: Get a quest information
      parameters:
        - $ref: '#/parameters/QuestID'
        - $ref: '#/parameters/Populate'
      responses:
        200:
          description: quest found
          schema:
            $ref: '#/definitions/Quest'
        404:
          description: quest not found
    put:
      operationId: updateQuest
      summary: Update a quest information
      parameters:
        - $ref: '#/parameters/QuestID'
        - name: information
          in: body
          required: true
          schema:
            $ref: '#/definitions/QuestUpdate'
      security:
        - Bearer: []
      responses:
        200:
          description: quest updated
          schema:
            $ref: '#/definitions/Quest'
        403:
          description: unauthorized access
        404:
          description: quest not found
    delete:
      operationId: deleteQuest
      summary: Deletes a quest
      parameters:
        - $ref: '#/parameters/QuestID'
      security:
        - Bearer: []
      responses:
        200:
          description: deletion success
        400:
          description: deletion failed
        403:
          description: unauthorized access
        404:
          description: quest not found
        405:
          description: cannot delete an ended quest
          headers:
            Allow:
              type: string
              description: Allowed methods
        409:
          description: cannot delete a quest with participants
  /quests/{id}/end:
    post:
      operationId: endQuest
      summary: Ends a quest and checks participants' ranks.
      parameters:
        - $ref: '#/parameters/QuestID'
      security:
        - Bearer: []
      responses:
        200:
          description: quest ended
          schema:
            $ref: '#/definitions/Quest'
        403:
          description: unauthorized access
        404:
          description: quest not found
  /participation:
    post:
      operationId: joinQuest
      summary: An adventurer joins a quest
      parameters:
        - name: adventurer
          description: Adventurer joining a quest.
          in: formData
          type: string
          required: true
        - name: quest
          description: Quest to join.
          in: formData
          type: integer
          format: int64
          required: true
      security:
        - Bearer: []
      responses:
        200:
          description: quest joined
        403:
          description: unauthorized access
        404:
          description: adventurer or quest not found
        405:
          description: cannot join an ended quest
          headers:
            Allow:
              type: string
              description: Allowed methods
    delete:
      operationId: quitQuest
      summary: An adventurer quits a quest
      parameters:
        - name: adventurer
          description: Adventurer joining a quest.
          in: formData
          type: string
          required: true
        - name: quest
          description: Quest to join.
          in: formData
          type: integer
          format: int64
          required: true
      security:
        - Bearer: []
      responses:
        200:
          description: quest quitted
        403:
          description: unauthorized access
        404:
          description: adventurer or quest not found
        405:
          description: cannot quit an ended quest
          headers:
            Allow:
              type: string
              description: Allowed methods
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
parameters:
  Limit:
    name: limit
    in: query
    type: integer
    required: false
    description: The quantity of elements to retrieve
  Offset:
    name: offset
    in: query
    type: integer
    required: false
    description: The number of elements to omit
  SortBy:
    name: sortby
    in: query
    type: string
    required: false
    description: The name of the data to sort by.
  Populate:
    name: populate
    in: query
    type: string
    required: false
    description: The name of the data to populate.
  Name:
    name: name
    in: path
    type: string
    required: true
    description: The name of an adventurer.
  QuestID:
    name: id
    in: path
    type: integer
    format: int64
    required: true
    description: The id of a quest.
definitions:
  Adventurer:
    type: object
    properties:
      name:
        type: string
      job:
        type: string
      rank:
        type: string
  AdventurerCreate:
    type: object
    properties:
      name:
        type: string
      job:
        type: string
  AdventurerUpdate:
    type: object
    properties:
      job:
        type: string
  Quest:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      description:
        type: string
      rank:
        type: string
      owner:
        type: string
      ended:
        type: boolean
  QuestCreate:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      rank:
        type: string
      owner:
        type: string
  QuestUpdate:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      rank:
        type: string
  Participation:
    type: object
    properties:
      adventurer:
        type: string
      quest:
        type: integer